grails:
    profile: plugin
    codegen:
        defaultPackage: simple.plugin
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'
environments:
    development:
        management:
            endpoints:
                enabled-by-default: true
                web:
                    base-path: '/actuator'
                    exposure:
                        include: '*'
    production:
        management:
            endpoints:
                enabled-by-default: false

rsa:
    public: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzLeWnkIP6KubeLR2uv7MHGsCvMeXNSdyQoJxWPcBTPJQwqwNIcBCuQHq44+crnJ1qLzSxt3jHq6fVd5vdL9rAXb44OO4eR0z+Y2EjczPhqOrWW+xAz4IiIs5tlHiE+vvSiXdWoYlRDMbWKawm8m4eDvqZzRdlKw2IOOXwWVqAP0f8Axr+ssu63DPkbmb9XYQXTsxHtzaTaGURgT2aM/Ma8crvwwlsahChARXDfp59IuyjH43M74xQ072W75NP8tXf94q3eNkXBsaOqttxu0hf35EW/p8oWuf+WYOJr8m4lC0drTeqGDVZdSJ6pSjI+Co/R5+JADQ15qw68qTMEw49QIDAQAB
    private: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDMt5aeQg/oq5t4tHa6/swcawK8x5c1J3JCgnFY9wFM8lDCrA0hwEK5Aerjj5yucnWovNLG3eMerp9V3m90v2sBdvjg47h5HTP5jYSNzM+Go6tZb7EDPgiIizm2UeIT6+9KJd1ahiVEMxtYprCbybh4O+pnNF2UrDYg45fBZWoA/R/wDGv6yy7rcM+RuZv1dhBdOzEe3NpNoZRGBPZoz8xrxyu/DCWxqEKEBFcN+nn0i7KMfjczvjFDTvZbvk0/y1d/3ird42RcGxo6q23G7SF/fkRb+nyha5/5Zg4mvybiULR2tN6oYNVl1InqlKMj4Kj9Hn4kANDXmrDrypMwTDj1AgMBAAECggEAPmh9XzOOfATMuahyRaFlgghRZlGGVCr5VzNC8LckS1vXqPEgc7iT3qip/cOLJVc5bT5bF0sPcQwVAO11lua/7UtipdRmKW3wqVQuI7hbT5VXqEU3dmCT42RmLKGbxSz43ubaKz2X4MmfvY/baTK+rNC/LcU1/hvdyHr5iXisLy5v2CdYzE+ZDobieADtuAkhGn9Wzq8xzRu6QQnfgRdGST8sH2C5whzZc6Kb005B3P6Tk0lEvj5UFu4clVGFR6GOim+OJDpKT1+Snyj9lRCQNJAoENTyVQ80MoxlBEm8ez20bsNeHTcjjXF7BnH8sN5vTS/0JH/lZm2MKNxpjK8UQQKBgQDmSnMO7ug5HGMA9jjSZbidxGe+1Av2ftm1nC30h3wvrDL2xpdkW1wX28YBEk9ZpLRo/G6kLe8EGM9EUnoB5tNn06fPiX34dwwhtMS1HA1v69xGacoh0suyU3Nn2/Yauf6AHjKE7s5C7Qe4Rfhr0wLWik1995f7U7y2yHQ1BRa/BQKBgQDjkkLY/s/P6vZfDhAl2C0qlxPhpA/I7x14yWKNPWGc0YzivVLtC722VJi0CPEwIh3u9ed3wwzecxwt+aidspnH38xOInTkqnbMW8aM0bJbL8+zy3QiwtEQit2NJ/y2289BUdyPDAlk8C6/A2DcxyIQeHAw2JIRq40Qv6DpSIFVMQKBgCGZlzQEk4lRpPhM9HluMgOC1og3NA+g7m7a/LGC2xGxlDYBP7F6yvMIM9mQLFet+kyfGB2IPilg3Uzgo8CHRy0M6p0TOHf6FqEMWO77ytIbnaYAZWeN8/5uwpXSuBOqM4HJ5iETHrERGGFAhEBnJzDaOPg6GcinrQ8WLC5YMbtpAoGACMZX+4P/wVWfAFVLfBoUy8KdiqLH1QibS1AAk8+dFu3hj9CbBPbh7sjeRnrdyexW2SL0NOL5eQ5ZNNCels4PLezMNOsRNMv53rFfO4jOZsO2L4mVxc1bQFcKaenzzZ02JZ+hcIaXSiQUuVrI/lpTTu1F7iw7naDOxKmO68/W5NECgYEAzIUBp0G83Zf+TG6V7If60392z+rwI1dHw1zs9MLGh5TlsTj2/4AuBT91VnidfSFnFDKoWQDo60Z5TfVhTEeUSvXbx49qXkaUha/Ua5t0Qol7yAehSJRbXAAOikU+2TPlN9uSGkcIvRFqxRlpbJ16T0r4qjIhACOoLGASvsV6CQY=
